# version: "3.10"
services:
  rtmp:
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935"
      - "8080:8080"

  backend:
    build: ./Back_end/backendstreaming
    ports:
      - "8081:8081"
    depends_on:
      - rtmp
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - backend_network

  frontend:
    build: ./Front_end/frontendstreaming
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - frontend_network

  database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=cntt15723
      - MYSQL_DATABASE=streaming_db
    ports:
      - "3307:3307"
    networks:
      - backend_network

networks:
  backend_network:
  frontend_network:
