services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: streaming_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "1935:1935"
    volumes:
      - ./nginx/nginx.conf:/usr/local/nginx/conf/nginx.conf:ro
      - ./nginx/rtmp.conf:/usr/local/nginx/conf/rtmp.conf:ro
      - ./data/hls:/usr/local/nginx/html/live
      - ./nginx/logs:/usr/local/nginx/logs
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backendlivestreaming
    container_name: backend
    environment:
      DB_HOST: mysql_db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: streaming_db
      DB_PORT: 3306
    ports:
      - "3000:3000"
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
